// Generated by https://quicktype.io
// Generated by https://quicktype.io

export interface TokenResponse {
  message: string;
  results: string;
}

export interface ResponseResuls {
  message: string;
  results: Results;
}

export interface Results {
  user:  User;
  token: string;
}

export interface User {
  _id:       string;
  name:      string;
  email:     string;
  password:  string;
  roles:     string[];
}

export interface LoginUser {
  email:     string;
  password:  string;
}
